### ISSUE TITLE
Can't install pgadmin

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/pgadmin_ynh#15]
Impossible to install pgadmin, any suggestion ?
https://paste.yunohost.org/raw/riwujoyesu
YunoHost 4.2.6.1

**Comment by tutle** [comment]
It 's possible to install by command line (putty) but not from the web admin console
Once installed, impossible to connect with username password...
Help !!! I would like so much to install a shared database for davinci resolve editing.
Sincerely

**Comment by Josue-T** [comment]
Looks like that it same than this https://github.com/YunoHost-Apps/pgadmin_ynh/issues/4

I close it as it probably a duplicate. Feel free to reopen if it's not the case.

**Comment by Josue-T** [comment]
For the credential issue it's explained here https://github.com/YunoHost-Apps/pgadmin_ynh/issues/2#issuecomment-854213241
