### ISSUE TITLE
can't install PgAdmin...

### ISSUE THREAD

**Issue by krrkrr** [YunoHost-Apps/pgadmin_ynh#8]
I got no pb with my YNH but it refuses to install PgAdmin... and I need it for Moodle...

I've tried with Moodle already installed:
https://paste.yunohost.org/raw/erarafumuz

and then, I've desintalled Moodle and tried again but:
https://paste.yunohost.org/raw/ugotutufel

Thanks for help....

**Comment by krrkrr** [comment]
anyone ?

**Comment by Josue-T** [comment]
Maybe can you try on debian buster ?

So it look like that in the sqlite database of PgAdmin there are no table `user` which is need for the configuration.
Maybe you can try to install to reinstall PgAdmin with the option `-n` which won't remove the app in failing case. After you can try to extract the sqlite database which is needed for the full configuration (it should be in `/var/lib/pgadmin/pgadmin4.db`) and check that this table exist. I use `sqlitebrowser` to see/edit a sqlite database on my Desktop.

**Comment by krrkrr** [comment]
on YNH forums, someone said it works on Buster... but migrating my YNH on buster now, is not a good idea... I got some critical features that are in use...

**Comment by krrkrr** [comment]
bah, I've tried to migrate... as it seems to be the only way to have PgAdmin... in despite of the case it is said to be ok on YNH 3.8.x ...

and it failed.
 https://paste.yunohost.org/raw/ujimukajiy

I'm stuck.

**Comment by Josue-T** [comment]
I didn't force you to migrate to buster.

And explained on the last post how you can try to localize the issue on stretch...

**Comment by krrkrr** [comment]
that didn't work... I had to reverse back with BackInTime ... that's why I've decided to migrate anyway...

**Comment by Josue-T** [comment]
> that didn't work... I had to reverse back with BackInTime ... that's why I've decided to migrate anyway...

What didn't work ?

**Comment by krrkrr** [comment]
Installing with -n .... and trying to figure out from there.

anyway, I've managed to upgrade to buster... with a lot of errors from the YNH scripts at first... and then, some CLI to finish that... 

I've tried to install PgAdmin... and it failed again. Here's the log:  https://paste.yunohost.org/raw/micuberewo

**Comment by Josue-T** [comment]
Hello,

So, firstly you look like really hangry. I could understand that you really need setup which works, it's not really my fault if it don't work. I help you on my free time so be just a little bit more cooperative.

Now, to help you to debug I need some information to understand why if fail. The issue is that the sqlite database of pgadmin don't the true content. So now I need to know what there are in actually. So can you share the this file : `/var/lib/pgadmin/pgadmin4.db` or can you see if there are a table `user` in this database. If you have Linux on your desktop you can use sqlitebrowser to see/edit this database.

**Comment by krrkrr** [comment]
no, no, no anger... just the fear that I will not have my moodle working for my students next week....

I'm gonna check that

**Comment by krrkrr** [comment]
there's no folder pgadmin in the /var/lib/  ... 

maybe it is because when it fails, it removes everything ? I need to install it with -n ? meaning, installing it in CLI and not in the YNH gui...

**Comment by Josue-T** [comment]
Yes

**Comment by krrkrr** [comment]
doing it rite now...

BTW, when I try to install PgAdmin, I got this error msg:
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/111/gvfs

is it important ?

**Comment by krrkrr** [comment]
er... something's just happened ??? after 3 or 4 tries this morning (using YNH GUI) on Buster...  now that I've tried to installed PgAdmin using terminal.... it worked ???!!!!! WTF ???? what would be the difference between YNH GUI and YNH CLI ??? There was no update between this morning and right now..... 

how can I try that it's properly installed ???

**Comment by krrkrr** [comment]
ah... there's still an issue: I can't log into PgAdmin... it does ack my admin log/pass ...  and of course, I've checked that carefully.

**Comment by Josue-T** [comment]
So is it OK ?

**Comment by krrkrr** [comment]
Sorry, I'm still trying to figure out other issues, due to the chaotic upgrade to buster... I'll try to import my moodle database asap...  just a short question: what would be the login ? as it is not recognized right now... I need to give PgAdmin the email from my admin user... and not the login... is there a way to check which login I should use ?

**Comment by Josue-T** [comment]
Hello,

I don't really understand your question. Normally in Pgadmin, the login username is always an email addresses. And normally it should be main email of the user that you say as admin. You can get this email with the command `yunohost user info USER`.

**Comment by krrkrr** [comment]
oh, ok. it's not obvious for me, as I deal with things with login/pass ... and eventually mail on the second hand. Ok, let's go with the mail. Rite now, it seems fine. thanks a lot for your help !!
